### ISSUE TITLE
Feedback JS Homework Week 2

### ISSUE THREAD

**Issue by remarcmij** [JawharBairakdar/HYF-2nd-Step#1]
Hi Mohamad,

Here is my feedback on your homework.

I'm afraid I couldn't check your work on questions 4 and 7-11 because you didn't adhere to what was asked for. See my remarks on those questions below.

Q1. Excellent. But it would make it easier for me to check your homework if you added an example call to your function with a `console.log` so that I can copy & paste your code, run it on my computer and check the result.

Q2. If I call your function I do not get the expected result:  
  
```js
console.log(colorCar('red'));
```

The output I get is `a red`. I was expecting to get `a red car`.

Q3. Excellent.

Q4, 7-11. It looks like you have let your fantasy run wild here. That makes it very difficult for me to review whether you have successfully answered the questions (remember, I have 13 homework submissions to check, which takes me a full day). Can you please go back to the simplest code necessary to answer the questions?

Q5. A simple `console.log(3 === 3)` would have done.

Q12. OK

Q13-14. How can I tell which teacher taught you what language?

Q15. While your code seems to output correctly, I'm afraid the implementation is not. Inside the `foo()` function you should not reference the `bar()` function. Instead you should call the function that was passed as an arguments to `foo()`

Q16. I missed your answer

Q17. I missed your answer

Q18. Excellent

**Comment by JawharBairakdar** [comment]
Hi and Thanks For Feed me Back,
Actually Yeah you have all the rights if you tell me I have a lot of mistakes at my code But i have an explain for that let's preview My Code together Quickly:
At the First question yes i do agree that for it and for the most of questions i have but the console is almost full and i want to follow my code one by one, I am so sorry let you rush at that moment.

It's Really simple and easy Just within Three Steps I WILL EDIT MY CODE FOR THAT:

1. Every Thing Around the vehicles.
2. Every Thing For Explaining _(What's happened with this code ...etc)_.
3. Any Thing Else.

For the first step you will find the code edited to be more readable.
For the second Step Here.
Third Step At code.
Q1. Solved Above.
Q2. Code.
Q3. Solved.
Q4. 7-11 Code AND The 6th Question also.
Q12. Solved.
Q13 + Q14. Code.
Q15. Yes This Is Wrong Actually i have saw it after i posted it on trello so i just didn't change any thing.
Q16. It's Just a miss understanding for the question it self (It's not equal each others because of the property type) And i have this one is wrong too.
Q17.

**Comment by JawharBairakdar** [comment]
Hi and thank you for feed me back,
Here you will find an explaining copy of my answers.
[https://github.com/JawharBairakdar/HYF-2nd-Step/blob/master/JsWeek2/Js-HYF-Week-2-Issues-solving.js](url)

I tried making it simple But I did my best hopefully 😃.
